[project]
name = "langgraph-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langgraph>=0.6.3",
    "notebook>=7.4.5",
    "python-dotenv>=1.1.1",
]
